### PR TITLE
fix error within API function which prevents user being subscribed to a channel

### PR DESCRIPTION
**Pull request by semteacher**
Found error:
$this->userapi->get_user 
expected int but object was provided... So users were unable to suscribe. Fixed.

### CODE REVIEW

**Comment by adpe** [comment]
Thanks @semteacher, for your good catch and your merge request - really appreciate!

I've look to that issue and found an inconsistency which could be solved in two ways. As I dig in to the code, I saw that the user is called twice.  Therefore, I've refactored slightly the logic and cleaned up the observers.

Can you please try out this branch https://github.com/adpe/moodle-local_rocketchat/tree/bugfix/12-user-subscriptions and let me know if it solves the problem at your end?

Greets
Adrian

**Comment by adpe** [comment]
This PR will be closed. Please follow https://github.com/adpe/moodle-local_rocketchat/pull/13

**Comment by semteacher** [comment]
Thank you @adpe  to pay attention to this problem. Will try to check ASAP but do not know when - I am from Ukraine and we fight against russia invasion for now....

**Comment by adpe** [comment]
Sad to hear about what's going on there! Please let me know in PR #13 or in the issue https://github.com/adpe/moodle-local_rocketchat/issues/12 if it will solve your problem.

If I'll have some spare time, I try to reproduce it and merge it if successful straight away and release a new plugin version.

Greets
Adrian

**Comment by adpe** [comment]
Hi @semteacher 

Could reproduce it and can verify that it's now working with Rocket.Chat 4.4.2. There were some other changes due to naming convention in channels as well, which breaks stuff...

Will release a new plugin version the next days.

Greets
Adrian

**Comment by semteacher** [comment]
Hi @adpe  
Nice to hear. Does not nave ability to work on this (even despite I am in relatively safe area)

**Pull request closed without merging**
